version: '3.8'
services:
  linux-module-01-disk-space-detective:
    build: .
    container_name: lab-08-disk-space-detective
    restart: "no"
    labels:
      - "lab.module=MODULE 01"
      - "lab.category=linux"
      - "lab.difficulty=beginner"
      - "lab.title=Disk Space Detective"
      - "lab.id=module-01-lab-08-disk-space-detective"
    volumes:
      - ./solution:/solution:ro
