"""Add gamification

Revision ID: 0c1e972043e9
Revises: f6c9cf301a78
Create Date: 2026-05-19 09:04:04.123116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0c1e972043e9'
down_revision: Union[str, None] = 'f6c9cf301a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('lab_id', sa.String(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.String(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('students', sa.Column('xp', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('longest_streak', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('last_activity_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'last_activity_date')
    op.drop_column('students', 'longest_streak')
    op.drop_column('students', 'current_streak')
    op.drop_column('students', 'level')
    op.drop_column('students', 'xp')
    op.drop_table('student_achievements')
    op.drop_table('daily_challenges')
    op.drop_table('achievements')
    # ### end Alembic commands ###
