"""auto

Revision ID: 21be2f9b1a77
Revises: 330dd385bf7c
Create Date: 2026-05-30 09:31:36.235805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '21be2f9b1a77'
down_revision: Union[str, None] = '330dd385bf7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('submissions_session_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'lab_sessions', ['session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_session_id_fkey'), 'submissions', 'lab_sessions', ['session_id'], ['id'])
    op.alter_column('submissions', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
