"""auto

Revision ID: 330dd385bf7c
Revises: 5c065b17d9c0
Create Date: 2026-05-29 15:22:15.886980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '330dd385bf7c'
down_revision: Union[str, None] = '5c065b17d9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_sessions', sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('lab_sessions', sa.Column('auto_stopped', sa.Boolean(), nullable=True))
    op.create_index('idx_student_status', 'lab_sessions', ['student_id', 'status'], unique=False)
    op.add_column('students', sa.Column('subscription_tier', sa.String(), nullable=True))
    op.add_column('students', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('students', sa.Column('opt_out_completion', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'opt_out_completion')
    op.drop_column('students', 'stripe_customer_id')
    op.drop_column('students', 'subscription_tier')
    op.drop_index('idx_student_status', table_name='lab_sessions')
    op.drop_column('lab_sessions', 'auto_stopped')
    op.drop_column('lab_sessions', 'last_activity_at')
    # ### end Alembic commands ###
