"""auto

Revision ID: 5c065b17d9c0
Revises: 0c1e972043e9
Create Date: 2026-05-20 04:57:14.586533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '5c065b17d9c0'
down_revision: Union[str, None] = '0c1e972043e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('solution', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'solution')
    # ### end Alembic commands ###
